/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ButtonsRouteImport } from './routes/buttons'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as etypePickRouteImport } from './routes/(etype)/pick'
import { Route as ApiPick1RouteImport } from './routes/api/pick1'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonsRoute = ButtonsRouteImport.update({
  id: '/buttons',
  path: '/buttons',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const etypePickRoute = etypePickRouteImport.update({
  id: '/(etype)/pick',
  path: '/pick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPick1Route = ApiPick1RouteImport.update({
  id: '/api/pick1',
  path: '/api/pick1',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/buttons': typeof ButtonsRoute
  '/learn': typeof LearnRoute
  '/pick': typeof etypePickRoute
  '/api/pick1': typeof ApiPick1Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/buttons': typeof ButtonsRoute
  '/learn': typeof LearnRoute
  '/pick': typeof etypePickRoute
  '/api/pick1': typeof ApiPick1Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/buttons': typeof ButtonsRoute
  '/learn': typeof LearnRoute
  '/(etype)/pick': typeof etypePickRoute
  '/api/pick1': typeof ApiPick1Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/404'
    | '/about'
    | '/buttons'
    | '/learn'
    | '/pick'
    | '/api/pick1'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/404'
    | '/about'
    | '/buttons'
    | '/learn'
    | '/pick'
    | '/api/pick1'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/404'
    | '/about'
    | '/buttons'
    | '/learn'
    | '/(etype)/pick'
    | '/api/pick1'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  ButtonsRoute: typeof ButtonsRoute
  LearnRoute: typeof LearnRoute
  etypePickRoute: typeof etypePickRoute
  ApiPick1Route: typeof ApiPick1Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buttons': {
      id: '/buttons'
      path: '/buttons'
      fullPath: '/buttons'
      preLoaderRoute: typeof ButtonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(etype)/pick': {
      id: '/(etype)/pick'
      path: '/pick'
      fullPath: '/pick'
      preLoaderRoute: typeof etypePickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pick1': {
      id: '/api/pick1'
      path: '/api/pick1'
      fullPath: '/api/pick1'
      preLoaderRoute: typeof ApiPick1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  ButtonsRoute: ButtonsRoute,
  LearnRoute: LearnRoute,
  etypePickRoute: etypePickRoute,
  ApiPick1Route: ApiPick1Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
